# Generated by Django 3.0.2 on 2020-04-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200409_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtaalaconte',
            name='mtaala',
        ),
        migrations.DeleteModel(
            name='Curricula',
        ),
        migrations.DeleteModel(
            name='MtaalaConte',
        ),
    ]
