# Generated by Django 3.0.2 on 2020-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20200409_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtaalahead',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='headers', to='teachers.MtaalaArticles'),
        ),
    ]
