# Generated by Django 3.0.2 on 2020-04-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20200409_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtaalahead',
            name='articles',
        ),
        migrations.AddField(
            model_name='mtaalaarticles',
            name='headers',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.MtaalaHead'),
            preserve_default=False,
        ),
    ]
